- name: spring_array1
  spec:
    - xByX         : 5.0 # 0.0
      d_pos        : 0.0025 #0.005
      density      : 1.0
      size_x       : 0.0525
      size_y       : 0.0525
      skin_height  : 0.04
      tac_height   : 0.03
      plane_height : 0.02
      sens_rad     : 1.0
      space_wid    : 4.0
- name: spring_array2
  spec:
    - xByX         : 5.0 # 0.0
      d_pos        : 0.0025 #0.005
      density      : 1.0
      size_x       : 0.0525
      size_y       : 0.0525
      skin_height  : 0.04
      tac_height   : 0.03
      plane_height : 0.02
      sens_rad     : 1.0
      space_wid    : 4.0

