- name: spring_board
  spec:
    # No of elements per side
    # do nothing if 0 use size_x and size_y
    - xByX         : 7.0 # 0.0
      d_pos        : 0.25 #0.005
      density      : 3.0
      size_x       : 0.0525
      size_y       : 0.0525
      skin_height  : 0.2
      tac_height   : 0.05
      plane_height : 0.001
      sens_rad     : 1.0
      space_wid    : 4.0
