# Configuration file for model generator
- name: skin_array
  spec:
      # Skin element and patch count
    - num_elements_x               : 8					# Number of skin elements per patch in x-direction
      num_elements_y               : 8					# Number of skin elements per patch in y-direction  (note: total number of elements per patch < 100)
      num_patches_x                : 1					# Number of skin patches in x-direction
      num_patches_y                : 1					# Number of skin patches in y-direction
      # Skin element properties
      element_diameter             : 0.010			 	# Diameter of each skin element [meters]
      element_height               : 0.010				# The height of the skin element from the ground [meters]
      element_mass                 : 0.0				# Mass of skin element [kg]
      element_spring               : 122.24				# Spring constant of skin element [N/m]
      element_damping              : 1.183				# Damping of skin element
      # Skin plane properties
      plane_thickness              : 0.002				# Thickness of the skin plane [meters]
      plane_height                 : 0.001				# The height of the plane from the ground [meters]
      # Skin array placement
      init_x                       : 0.0				# Initial x position [meters]
      init_y                       : 0.0				# Initial y position [meters]
      init_z                       : 0.03				# Initial z position [meters]
      parent                       : world				# Name of parent link
      # Data collection with ROS
      ros_namespace                : skinsim			# Namespace for ROS topic
      update_rate                  : 0.0				# Update rate of plugin (0 means as fast as possible)
      # TODO: override count settings if length > 0
      patch_length_x               : 0.0				# Length of skin patch in x-direction
      patch_length_y               : 0.0				# Length of skin patch in y-direction
      total_length_x               : 0.0				# Length of skin array in x-direction
      total_length_y               : 0.0				# Length of skin array in y-direction
      # Tactile sensor properties
      tactile_elements_x           : 2					# Number of skin elements per sensor in x-direction
      tactile_elements_y           : 2					# Number of skin elements per sensor in y-direction
      tactile_separation_x         : 1					# Spaceing between sensors in terms of number of elements in x-direction
      tactile_separation_y         : 1					# Spaceing between sensors in terms of number of elements in x-direction
      # TODO add plunger properties
