density      : 1.0
size_x       : 0.01
size_y       : 0.01

skin_height  : 0.04
tac_height   : 0.03

plane_height : 0.02

d_pos        : 0.0025

sens_x       : 2.0
sens_y       : 4.0
space_x      : 1.0
space_y      : 1.0
